/**
 * Agent execution — boundary between Arka orchestration and an external
 * coding-agent runtime. The port deliberately carries no project state:
 * callers own durable execution records and only pass a bounded mission.
 */

export type AgentExecutionProvider = "codex-acp" | "claude";

export type AgentExecutionStatus = "running" | "awaiting_approval" | "completed" | "failed" | "cancelled" | "interrupted";

/**
 * ACP sessions cannot be resumed after an interrupted process. Retrying always
 * starts a fresh provider run, even when a provider has its own session API.
 */
export type AgentExecutionRetryStrategy = "new-run";

/**
 * A preauthorized workspace policy is deliberately descriptive rather than an
 * automatic provider grant: current ACP permission requests do not contain a
 * portable enough path/command contract to prove that an action is in scope.
 */
export type AgentExecutionPermissionPolicy =
  | "deny-all"
  | {
    readonly mode: "preauthorized-workspace";
    readonly scopePaths: readonly string[];
    readonly permissions: readonly ("read_workspace" | "write_workspace")[];
  };

export interface AgentExecutionBaseMission {
  /** Caller-owned stable identifier; never generated by the adapter. */
  readonly executionId: string;
  /** Bounded provider prompt. It is never logged by the adapter. */
  readonly mission: string;
  /** Absolute work directory for the external harness. */
  readonly workspace: string;
  /**
   * Omission means deny-all. A preauthorized workspace order is carried to the
   * worker but never turns an opaque provider permission request into an
   * automatic grant; it becomes awaiting_approval and requires a new run.
   */
  readonly permissionPolicy?: AgentExecutionPermissionPolicy;
  /**
   * Non-secret locale/display variables only. Credentials and arbitrary
   * inherited environment variables are intentionally unsupported.
   */
  readonly safeEnvironment?: Readonly<Record<string, string>>;
  /** Hard execution limit in milliseconds. */
  readonly timeoutMs?: number;
  /** Cancels the running external process and triggers cleanup. */
  readonly signal?: AbortSignal;
}

/**
 * A Codex-compatible ACP harness must be installed separately and supplied as
 * an absolute executable path. No package manager launcher is used here.
 */
export interface CodexAcpExecutionMission extends AgentExecutionBaseMission {
  readonly provider: "codex-acp";
  readonly command: string;
  readonly args?: readonly string[];
  readonly authMethodId?: string;
  readonly model?: string;
}

export interface ClaudeExecutionMission extends AgentExecutionBaseMission {
  readonly provider: "claude";
  readonly model?: string;
}

export type AgentExecutionMission = CodexAcpExecutionMission | ClaudeExecutionMission;

export interface AgentExecutionFailure {
  readonly code: string;
  readonly message: string;
  readonly retryable: boolean;
}

export interface AgentExecutionApproval {
  readonly code: "permission_requested";
  readonly message: string;
  readonly retryStrategy: AgentExecutionRetryStrategy;
}

/**
 * Safe, inspectable execution state. The mission, environment and raw provider
 * stderr are deliberately omitted so callers do not accidentally persist them.
 */
export interface AgentExecutionOutcome {
  readonly executionId: string;
  readonly provider: AgentExecutionProvider;
  readonly workspace: string;
  readonly status: AgentExecutionStatus;
  readonly attempt: number;
  readonly retryStrategy: AgentExecutionRetryStrategy;
  readonly startedAt: string;
  readonly completedAt?: string;
  readonly output?: string;
  readonly sessionId?: string;
  readonly failure?: AgentExecutionFailure;
  readonly approval?: AgentExecutionApproval;
}

export interface AgentExecutionPort {
  dispatch(mission: AgentExecutionMission): Promise<AgentExecutionOutcome>;
  inspect(input: { readonly executionId: string }): Promise<AgentExecutionOutcome | undefined>;
  cancel(input: { readonly executionId: string }): Promise<AgentExecutionOutcome>;
  retry(input: { readonly executionId: string; readonly newExecutionId: string }): Promise<AgentExecutionOutcome>;
}
